[global]
developmentMode = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor       = "#1155A4"
backgroundColor    = "#F0F4F8"
secondaryBackgroundColor = "#FFFFFF"
textColor          = "#0D2137"
font               = "sans serif"